# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regkey', models.CharField(max_length=255, unique=True)),
                ('already_used', models.BooleanField(default=False)),
            ],
        ),
    ]
