# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='short',
            field=models.CharField(default='Server was in the way of the game, man!', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='Server Outage', max_length=40),
            preserve_default=False,
        ),
    ]
