# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20181216_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
