# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuelogentry',
            options={'ordering': ['-created_on']},
        ),
    ]
